
ion_src += $(addprefix ion/src/simulator/nspire/, \
  main.cpp \
  clipboard.cpp \
  display.cpp \
  framebuffer.cpp \
  telemetry_init.cpp \
  keyboard.cpp \
  events_keyboard.cpp \
  events.cpp \
  timing.cpp \
  console.cpp \
)

ion_src += ion/src/shared/collect_registers.cpp

sdl_simu_needs_to_be_removed += $(addprefix ion/src/simulator/shared/, \
  dummy/display.cpp \
  dummy/led.cpp \
  dummy/usb.cpp \
  dummy/battery.cpp \
  clipboard.cpp \
  display.cpp \
  events_keyboard.cpp \
  events_platform.cpp \
  events.cpp \
  framebuffer.cpp \
  keyboard.cpp \
  main.cpp \
  layout.cpp \
  dummy/store_script.cpp \
  actions.cpp \
  window.cpp \
  timing.cpp \
  console.cpp \
)

# Remove the dummy diplay (re-implemented) and the SDL simulator stuff.
ion_src := $(filter-out $(sdl_simu_needs_to_be_removed),$(ion_src))

SFLAGS := $(filter-out -Iion/src/simulator/external/sdl/include,$(SFLAGS))
